Add MacOS compatibility changes to invert_elastix

diff --git a/invert_elastix b/invert_elastix
--- a/invert_elastix
+++ b/invert_elastix
@@ -1,10 +1,23 @@
 #!/bin/bash
 
+SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+
+# Configure paths and default parameters
+source run_elastix_settings
+elastix_folder=$(ls $elastix_installation_location/elastix-*/bin/elastix)
+if [ -z "$elastix_folder" ]; then
+    >&2 echo "elastix could not be found in $elastix_installation_location"
+    >&2 echo "Make sure you have downloaded elastix and then edited ${SCRIPT_DIR}/run_elastix_settings to specify where you put the elastix files"
+    exit 1
+fi
+elastix_folder=${elastix_folder%/bin/elastix}
+export PATH=$elastix_folder/bin:$PATH
+export LD_LIBRARY_PATH=$elastix_folder/lib
+
+
 show_help () {
     >&2 echo "Usage: invert_elastix folder_containing_transform_to_invert [-v] [-f] [-o output_suffix] [-n n_threads] [-s spacings] [-w]"
     >&2 echo "Example: ./invert_elastix ../motor_neurons/21G01-LexA/21G01LexA_vnc2_60x_T1_2019_09_19_neuropil_elastix_to_moving_template/elastix_Bspline/4spacing_20bendingweight"
-    >&2 echo "        Description goes here"
-    >&2 echo "        and can continue here"
 }
 
 if [ "$#" -eq 0 ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
@@ -12,12 +25,23 @@ if [ "$#" -eq 0 ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
     exit 1
 fi
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 if [ ! -f ${SCRIPT_DIR}/elastixParams_InvertBspline.txt ]; then
     show_help
-    >&2 echo "ERROR: elastixParams_InvertBspline.txt must exist in current directory"
+    >&2 echo "ERROR: elastixParams_InvertBspline.txt must exist in ${SCRIPT_DIR}"
     exit 1
 fi
+
+
+# Check whether the GNU sed or BSD/MacOS sed is installed and use
+# the form of the -i argument required by the detected version
+# Information from https://stackoverflow.com/a/44864004
+# Implementation from https://stackoverflow.com/a/9323261
+if sed --version &> /dev/null; then
+    dashi=(-i)  # GNU sed
+else
+    dashi=(-i "")  # BSD/MacOS sed
+fi
+
 
 #DEFAULTS FOR ARGUMENT-MODIFIABLE VARIABLES GO HERE
 verbose=false
@@ -167,8 +191,8 @@ for spacing in $spacings; do
         case $input in [yY]) echo "Overwriting"; chmod +w "$elastixParams";; *) echo "Exiting"; exit 1 ;; esac
     fi 
     cp "${SCRIPT_DIR}/elastixParams_InvertBspline.txt" "$elastixParams"
-    sed -i "s/(FinalGridSpacingInPhysicalUnits _GRIDSPACING_)/(FinalGridSpacingInPhysicalUnits $spacing)/" "$elastixParams"
-    if $write_intermediate_output; then sed -i 's/(WriteResultImage "false")/(WriteResultImage "true")/' "$elastixParams"; fi
+    sed "${dashi[@]}" "s/(FinalGridSpacingInPhysicalUnits _GRIDSPACING_)/(FinalGridSpacingInPhysicalUnits $spacing)/" "$elastixParams"
+    if $write_intermediate_output; then sed "${dashi[@]}" 's/(WriteResultImage "false")/(WriteResultImage "true")/' "$elastixParams"; fi
     $chmod -w "$elastixParams"
 
     echo "Inverting $base/TransformParameters.0.txt with GridSpacing $spacing"
@@ -187,7 +211,7 @@ for spacing in $spacings; do
     if [ -f "$output_folder/result.0.nrrd" ]; then $mv "$output_folder/result.0.nrrd" "$output_folder/result.0.composedForwardAndInverseTransforms.nrrd"; fi
 
     $cp "$output_folder/TransformParameters.0.txt" "$output_folder/TransformParameters.1.txt"
-    $sed -i 's/(InitialTransformParametersFileName.*)/(InitialTransformParametersFileName "NoInitialTransform")/' "$output_folder/TransformParameters.1.txt"
+    $sed "${dashi[@]}" 's/(InitialTransformParametersFileName.*)/(InitialTransformParametersFileName "NoInitialTransform")/' "$output_folder/TransformParameters.1.txt"
 
     #Apply the inverted transform to the fixed image
     $transformix -in "$fixed" \
